### PR TITLE
add meta storage

### PR DESCRIPTION
**Pull request by juliangruber**
so you can for example do

```js
manager.create({
  name: 'cute-cats',
  directory: driveLocation,
  meta: { owner: true }
})

manager.list((err, drives) => {
  assert(drives[0].meta.owner)
})
```

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
What's the use case for storing more data? - also this'll most definitely
conflict with the archivist branch (thing I've been working on yesterday
https://github.com/yoshuawuyts/multidrive/tree/archivist) - can port if we
got a good use case for it tho (:

**Comment by juliangruber** [comment]
I need to store `archive.owner = <Boolean>` per archive

**Comment by yoshuawuyts** [comment]
I don't think we need this anymore, do we?

**Comment by juliangruber** [comment]
yep, fortunately!

**Pull request closed without merging**
